---
kind: Service
apiVersion: v1
metadata:
  name: cloudlab6mapservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      port: 80
  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudlab6mapdeployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: kenlomax/cloudlab620190321:v3
          ports:
            - containerPort: 80